# Generated by Django 3.1.1 on 2020-09-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
    ]
